# A list of registry ids of dimensions players cannot travel to at all.
disabledDimensions = ["minecraft:the_end", "minecraft:nether","lostcities:lostcity"]
#
# Whether to push the player back or not when not meeting the requirements to access a dimension.
pushBackPlayer = false

